### ISSUE TITLE
Game crash on settlement re-take.

### ISSUE THREAD

**Issue by Ben-Ryder** [Ben-Ryder/NEA#9]
**Describe the bug**
Game crashes on retake of settlement

**To Reproduce**
Steps to reproduce the behaviour:
- Player1 takes a settlement
- Player2 tries to take it off them
- crashes with error text below

**Expected behaviour**

**Screenshots**
```
Traceback (most recent call last):
  File "D:\NEA-master\NEA-master\main.py", line 12, in <module>
    main()
  File "D:\NEA-master\NEA-master\main.py", line 8, in main
    controller.run()
  File "D:\NEA-master\NEA-master\NEA\control\controller.py", line 48, in run
    self.run_game(name)
  File "D:\NEA-master\NEA-master\NEA\control\controller.py", line 57, in run_game
    self.state = running_game.play()
  File "D:\NEA-master\NEA-master\NEA\game\controller.py", line 23, in play
    self.state = self.GUI.run()  # at finish, return new state wanted, either menu, quit or ended (game finished)
  File "D:\NEA-master\NEA-master\NEA\game\gui.py", line 76, in run
    self.handle_click(mouse_x, mouse_y)
  File "D:\NEA-master\NEA-master\NEA\game\gui.py", line 91, in handle_click
    self.game_view.handle_unit_actions()
  File "D:\NEA-master\NEA-master\NEA\game\view.py", line 91, in handle_unit_actions
    self.model.conquer(self.active_unit.position)  # not returning as know can conquer at this point
  File "D:\NEA-master\NEA-master\NEA\game\model.py", line 84, in conquer
    settlement.current_holder.remove_settlement(settlement)
  File "D:\NEA-master\NEA-master\NEA\game\model.py", line 202, in remove_settlement
    self.settlements.remove(reference)
ValueError: list.remove(x): x not in list
```

**Additional context**

**Comment by Ben-Ryder** [comment]
Solved with latest commit. forgot to append settlement to `current_player` settlement list when capturing, but still transferred ownership from `city.chage_owner()`, meaning went to delete settlement on capture that wasn't there.
